In [1]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

In [2]:
df = pd.read_csv('DataAnalyst.csv')
df.head()

,No.,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,TRUE
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,TRUE

# Salary Cleaning

In [3]:
df = df[df['Salary Estimate'] != '-1']
df.count()

No.                  2251
Job Title            2251
Salary Estimate      2251
Job Description      2251
Rating               2251
Company Name         2251
Location             2251
Headquarters         2251
Size                 2251
Founded              2251
Type of ownership    2251
Industry             2251
Sector               2251
Revenue              2251
Competitors          2251
Easy Apply           2251
dtype: int64

In [4]:
salary=df['Salary Estimate'].apply(lambda x: x.split('(')[0])
salary.head()

0    $37K-$66K
1    $37K-$66K
2    $37K-$66K
3    $37K-$66K
4    $37K-$66K
Name: Salary Estimate, dtype: object

In [5]:
removeK=salary.apply(lambda x: x.replace('K','').replace('$',''))
removeK.head()

0    37-66
1    37-66
2    37-66
3    37-66
4    37-66
Name: Salary Estimate, dtype: object

In [6]:
#check if there is salary stated in hourly rate
df['Hourly']=df['Salary Estimate'].apply(lambda x: 1 if 'per hour' in x.lower() else 0)
df['Hourly'].value_counts()

0    2251
Name: Hourly, dtype: int64

In [7]:
#Create new columns for minimum,maximum and average salary
df['Annual min_salary'] = removeK.apply(lambda x: int(x.split('-')[0]))
df['Annual max_salary'] = removeK.apply(lambda x: int(x.split('-')[1]))
df['Annual avg_salary'] = (df['Annual min_salary']+df['Annual max_salary'])/2
df.head()

,No.,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Hourly,Annual min_salary,Annual max_salary,Annual avg_salary
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,TRUE,0,37,66,51.5
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,0,37,66,51.5
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,0,37,66,51.5
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,0,37,66,51.5
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,TRUE,0,37,66,51.5

# Company Name Cleaning

In [8]:
#Removing the rating and /n in Company Name
df['CompanyName'] = df.apply(lambda x: x['Company Name'] if x['Rating'] <0 else x['Company Name'][:-4], axis = 1)
df.head()

,No.,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,Easy Apply,Hourly,Annual min_salary,Annual max_salary,Annual avg_salary,CompanyName
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,...,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,TRUE,0,37,66,51.5,Vera Institute of Justice
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,...,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,0,37,66,51.5,Visiting Nurse Service of New York
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,...,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,0,37,66,51.5,Squarespace
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,...,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,0,37,66,51.5,Celerity
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,...,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,TRUE,0,37,66,51.5,FanDuel

In [9]:
df['CompanyName'].value_counts()

Staffigo Technical Services, LLC             58
Diverse Lynx                                 22
Kforce                                       19
Lorven Technologies Inc                      19
Mondo                                        14
                                             ..
Fast Switch, LTD                              1
El Hogar del Nino - The Home of the Child     1
Empire Today                                  1
Numerator                                     1
SCL Health                                    1
Name: CompanyName, Length: 1501, dtype: int64

# Location Cleaning

In [10]:
df['State_Location'] = df['Location'].apply(lambda x: x.split(',')[1])
df.head()

,No.,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Sector,Revenue,Competitors,Easy Apply,Hourly,Annual min_salary,Annual max_salary,Annual avg_salary,CompanyName,State_Location
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,...,Non-Profit,$100 to $500 million (USD),-1,TRUE,0,37,66,51.5,Vera Institute of Justice,NY
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,...,Health Care,$2 to $5 billion (USD),-1,-1,0,37,66,51.5,Visiting Nurse Service of New York,NY
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,...,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,0,37,66,51.5,Squarespace,NY
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,...,Information Technology,$50 to $100 million (USD),-1,-1,0,37,66,51.5,Celerity,NY
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,...,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,TRUE,0,37,66,51.5,FanDuel,NY

In [11]:
df.State_Location.value_counts()

 CA          626
 TX          394
 NY          345
 IL          164
 PA          114
 AZ           97
 NC           89
 CO           88
 NJ           86
 WA           53
 VA           48
 OH           35
 UT           33
 FL           27
 IN           23
 DE           11
 Arapahoe      8
 GA            4
 KS            3
 SC            3
Name: State_Location, dtype: int64

In [12]:
#Fix Arapahoe to Colorado(CO)
replace2CO=df.State_Location.apply(lambda x: x.replace('Arapahoe','CO'))
df['State_Location'] = replace2CO
df.State_Location.value_counts()

 CA    626
 TX    394
 NY    345
 IL    164
 PA    114
 AZ     97
 CO     96
 NC     89
 NJ     86
 WA     53
 VA     48
 OH     35
 UT     33
 FL     27
 IN     23
 DE     11
 GA      4
 SC      3
 KS      3
Name: State_Location, dtype: int64

# Company Age Cleaning

In [13]:
df['Founded'].describe()

count    2251.000000
mean     1398.876944
std       901.758003
min        -1.000000
25%        -1.000000
50%      1979.000000
75%      2002.000000
max      2019.000000
Name: Founded, dtype: float64

In [14]:
df['Founded'].value_counts()

-1       659
 2008     80
 2000     54
 2002     54
 1996     54
        ...
 1958      1
 1885      1
 1922      1
 1830      1
 1898      1
Name: Founded, Length: 161, dtype: int64

In [15]:
#Dropping rows with Founder year = -1
df = df[df['Founded'] >= 0]
df['Founded'].describe()

count    1592.000000
mean     1978.348618
std        47.833946
min      1682.000000
25%      1970.000000
50%      1997.000000
75%      2006.000000
max      2019.000000
Name: Founded, dtype: float64

In [16]:
df['Founded'].value_counts()

2008    80
1996    54
2002    54
2000    54
1999    53
        ..
1830     1
1887     1
1895     1
1818     1
1905     1
Name: Founded, Length: 160, dtype: int64

In [17]:
df['Age'] = df.Founded.apply(lambda x: x if x <1 else 2022 - x)
df.count()

No.                  1592
Job Title            1592
Salary Estimate      1592
Job Description      1592
Rating               1592
Company Name         1592
Location             1592
Headquarters         1592
Size                 1592
Founded              1592
Type of ownership    1592
Industry             1592
Sector               1592
Revenue              1592
Competitors          1592
Easy Apply           1592
Hourly               1592
Annual min_salary    1592
Annual max_salary    1592
Annual avg_salary    1592
CompanyName          1592
State_Location       1592
Age                  1592
dtype: int64

In [18]:
#Check if Age is in the Dataframe
df.head()

,No.,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Revenue,Competitors,Easy Apply,Hourly,Annual min_salary,Annual max_salary,Annual avg_salary,CompanyName,State_Location,Age
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,...,$100 to $500 million (USD),-1,TRUE,0,37,66,51.5,Vera Institute of Justice,NY,61
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,...,$2 to $5 billion (USD),-1,-1,0,37,66,51.5,Visiting Nurse Service of New York,NY,129
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,...,Unknown / Non-Applicable,GoDaddy,-1,0,37,66,51.5,Squarespace,NY,19
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,...,$50 to $100 million (USD),-1,-1,0,37,66,51.5,Celerity,NY,20
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,...,$100 to $500 million (USD),DraftKings,TRUE,0,37,66,51.5,FanDuel,NY,13

# Industry & Sector Cleaning

In [19]:
#Dropping rows with Industry and Sector = -1
df = df[df['Industry'] != '-1']
df.count()

No.                  1575
Job Title            1575
Salary Estimate      1575
Job Description      1575
Rating               1575
Company Name         1575
Location             1575
Headquarters         1575
Size                 1575
Founded              1575
Type of ownership    1575
Industry             1575
Sector               1575
Revenue              1575
Competitors          1575
Easy Apply           1575
Hourly               1575
Annual min_salary    1575
Annual max_salary    1575
Annual avg_salary    1575
CompanyName          1575
State_Location       1575
Age                  1575
dtype: int64

In [20]:
df = df[df['Sector'] != '-1']
df.count()

No.                  1575
Job Title            1575
Salary Estimate      1575
Job Description      1575
Rating               1575
Company Name         1575
Location             1575
Headquarters         1575
Size                 1575
Founded              1575
Type of ownership    1575
Industry             1575
Sector               1575
Revenue              1575
Competitors          1575
Easy Apply           1575
Hourly               1575
Annual min_salary    1575
Annual max_salary    1575
Annual avg_salary    1575
CompanyName          1575
State_Location       1575
Age                  1575
dtype: int64

# Rating Cleaning

In [21]:
#Check current Rating values
df.Rating.value_counts()

 3.9    130
 3.7    115
 3.6    111
 3.8    109
 3.5    103
 4.1     97
 3.3     95
 4.0     85
 5.0     85
 3.4     81
 3.2     72
 3.1     62
 4.3     45
 4.5     41
 3.0     37
 4.6     37
 4.2     37
 2.8     35
 2.9     32
 4.4     30
 4.8     26
 2.7     24
 4.7     17
 4.9     16
-1.0     16
 2.5     12
 2.4      8
 2.6      7
 2.1      2
 2.2      2
 2.3      2
 2.0      1
 1.0      1
 1.9      1
 1.8      1
Name: Rating, dtype: int64

In [22]:
#Remove Ratings = -1
df = df[df['Rating'] >= 0]
df.count()

No.                  1559
Job Title            1559
Salary Estimate      1559
Job Description      1559
Rating               1559
Company Name         1559
Location             1559
Headquarters         1559
Size                 1559
Founded              1559
Type of ownership    1559
Industry             1559
Sector               1559
Revenue              1559
Competitors          1559
Easy Apply           1559
Hourly               1559
Annual min_salary    1559
Annual max_salary    1559
Annual avg_salary    1559
CompanyName          1559
State_Location       1559
Age                  1559
dtype: int64

# Revenue Cleaning

In [23]:
#Check Revenue Values
df.Revenue.value_counts()

Unknown / Non-Applicable            353
$100 to $500 million (USD)          207
$50 to $100 million (USD)           191
$10+ billion (USD)                  186
$2 to $5 billion (USD)              127
$10 to $25 million (USD)            112
$25 to $50 million (USD)             90
$1 to $2 billion (USD)               86
$500 million to $1 billion (USD)     75
$5 to $10 billion (USD)              56
$1 to $5 million (USD)               40
$5 to $10 million (USD)              26
Less than $1 million (USD)           10
Name: Revenue, dtype: int64

In [24]:
#Remove Revenue = Unkown/ Non-applicable
df = df[df['Revenue'] != 'Unknown / Non-Applicable']
df.count()

No.                  1206
Job Title            1206
Salary Estimate      1206
Job Description      1206
Rating               1206
Company Name         1206
Location             1206
Headquarters         1206
Size                 1206
Founded              1206
Type of ownership    1206
Industry             1206
Sector               1206
Revenue              1206
Competitors          1206
Easy Apply           1206
Hourly               1206
Annual min_salary    1206
Annual max_salary    1206
Annual avg_salary    1206
CompanyName          1206
State_Location       1206
Age                  1206
dtype: int64

# Competitors Cleaning

In [25]:
#Check Competitors Values
df.Competitors.value_counts()

-1                                                                 771
Adecco, Manpower                                                    14
Robert Half, Insight Global                                         14
TEKsystems, Insight Global, Accenture                               10
Google, Microsoft, Samsung Electronics                              10
                                                                  ...
Fiserv, First Data, Jack Henry & Associates                          1
Booz Allen Hamilton, Abt Associates, Oliver Wyman                    1
DP Electric, Helix Electric, Wilson Electric                         1
Big O Tires, Les Schwab Tire Centers, Pep Boys                       1
Centura Health, HealthONE, Denver Health and Hospital Authority      1
Name: Competitors, Length: 234, dtype: int64

In [26]:
#Replace Competitors value of -1 to NA
replace2NA=df.Competitors.apply(lambda x: x.replace('-1','NA'))
df['Competitors']=replace2NA
df.Competitors.value_counts()

NA                                                                 771
Adecco, Manpower                                                    14
Robert Half, Insight Global                                         14
TEKsystems, Insight Global, Accenture                               10
Google, Microsoft, Samsung Electronics                              10
                                                                  ...
Fiserv, First Data, Jack Henry & Associates                          1
Booz Allen Hamilton, Abt Associates, Oliver Wyman                    1
DP Electric, Helix Electric, Wilson Electric                         1
Big O Tires, Les Schwab Tire Centers, Pep Boys                       1
Centura Health, HealthONE, Denver Health and Hospital Authority      1
Name: Competitors, Length: 234, dtype: int64

In [27]:
#Check total dataset values
df.count()

No.                  1206
Job Title            1206
Salary Estimate      1206
Job Description      1206
Rating               1206
Company Name         1206
Location             1206
Headquarters         1206
Size                 1206
Founded              1206
Type of ownership    1206
Industry             1206
Sector               1206
Revenue              1206
Competitors          1206
Easy Apply           1206
Hourly               1206
Annual min_salary    1206
Annual max_salary    1206
Annual avg_salary    1206
CompanyName          1206
State_Location       1206
Age                  1206
dtype: int64

# Size Cleaning

In [28]:
#Check Size Values
df.Size.value_counts()

10000+ employees           320
1001 to 5000 employees     256
51 to 200 employees        223
201 to 500 employees       146
501 to 1000 employees      134
5001 to 10000 employees     78
1 to 50 employees           49
Name: Size, dtype: int64

# Job Text/Description Cleaning

In [29]:
#Check Job Text/Description data
df['Job Description'].head()

0    Are you eager to roll up your sleeves and harn...
1    Overview\n\nProvides analytical and technical ...
3    Requisition NumberRR-0001939\nRemote:Yes\nWe c...
4    ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...
7    Data Science Analyst\n\nJob Details\nLevel\nEx...
Name: Job Description, dtype: object

In [30]:
#Remove \n from Job Descriptions
df['Text/Description']=df['Job Description'].apply(lambda x: x.replace('\n', ' '))

In [31]:
df['Text/Description'].head()

0    Are you eager to roll up your sleeves and harn...
1    Overview  Provides analytical and technical su...
3    Requisition NumberRR-0001939 Remote:Yes We col...
4    ABOUT FANDUEL GROUP  FanDuel Group is a world-...
7    Data Science Analyst  Job Details Level Experi...
Name: Text/Description, dtype: object

In [32]:
#Check number of data again
df['Text/Description'].describe()

count                                                  1206
unique                                                 1206
top       Are you eager to roll up your sleeves and harn...
freq                                                      1
Name: Text/Description, dtype: object

# Job Title Cleaning

In [33]:
#Segregate to different roles/seniorirty in company
def title_simplifier(title):
    if 'manager' in title.lower() or 'project manager' in title.lower() or 'data manager' in title.lower() or 'data scientist manager' in title.lower():
        return 'Manager'
    elif 'data science' in title.lower():
        return 'Data scientist'
    elif 'data engineer' in title.lower():
        return 'Data engineer'
    elif 'analyst' in title.lower():
        return 'Analyst'
    else:
        return 'na'
    
def seniority(title):
    if 'sr' in title.lower() or 'senior' in title.lower() or 'sr' in title.lower() or 'lead' in title.lower() or 'director' in title.lower() or'principal' in title.lower():
            return 'Senior'
    elif 'jr' in title.lower() or 'jr.' in title.lower() or 'intern' in title.lower():
        return 'Junior'
    else:
        return 'Full time associate'

In [34]:
df['JobSpilt']=df['Job Title'].apply(title_simplifier)
df.JobSpilt.value_counts()

Analyst           1165
Data scientist      18
Manager             12
Data engineer       11
Name: JobSpilt, dtype: int64

In [35]:
df['SeniorityRoles']=df['Job Title'].apply(seniority)
df.SeniorityRoles.value_counts()

Full time associate    919
Senior                 274
Junior                  13
Name: SeniorityRoles, dtype: int64

In [36]:
df.head()

,No.,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Hourly,Annual min_salary,Annual max_salary,Annual avg_salary,CompanyName,State_Location,Age,Text/Description,JobSpilt,SeniorityRoles
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,...,0,37,66,51.5,Vera Institute of Justice,NY,61,Are you eager to roll up your sleeves and harn...,Analyst,Full time associate
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,...,0,37,66,51.5,Visiting Nurse Service of New York,NY,129,Overview Provides analytical and technical su...,Analyst,Full time associate
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,...,0,37,66,51.5,Celerity,NY,20,Requisition NumberRR-0001939 Remote:Yes We col...,Analyst,Full time associate
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,...,0,37,66,51.5,FanDuel,NY,13,ABOUT FANDUEL GROUP FanDuel Group is a world-...,Analyst,Full time associate
7,7,Data Science Analyst,$37K-$66K (Glassdoor est.),Data Science Analyst\n\nJob Details\nLevel\nEx...,3.7,GNY Insurance Companies\n3.7,"New York, NY","New York, NY",201 to 500 employees,1914,...,0,37,66,51.5,GNY Insurance Companies,NY,108,Data Science Analyst Job Details Level Experi...,Data scientist,Full time associate

# Overall Checking

In [37]:
df.head()

,No.,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Hourly,Annual min_salary,Annual max_salary,Annual avg_salary,CompanyName,State_Location,Age,Text/Description,JobSpilt,SeniorityRoles
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,...,0,37,66,51.5,Vera Institute of Justice,NY,61,Are you eager to roll up your sleeves and harn...,Analyst,Full time associate
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,...,0,37,66,51.5,Visiting Nurse Service of New York,NY,129,Overview Provides analytical and technical su...,Analyst,Full time associate
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,...,0,37,66,51.5,Celerity,NY,20,Requisition NumberRR-0001939 Remote:Yes We col...,Analyst,Full time associate
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,...,0,37,66,51.5,FanDuel,NY,13,ABOUT FANDUEL GROUP FanDuel Group is a world-...,Analyst,Full time associate
7,7,Data Science Analyst,$37K-$66K (Glassdoor est.),Data Science Analyst\n\nJob Details\nLevel\nEx...,3.7,GNY Insurance Companies\n3.7,"New York, NY","New York, NY",201 to 500 employees,1914,...,0,37,66,51.5,GNY Insurance Companies,NY,108,Data Science Analyst Job Details Level Experi...,Data scientist,Full time associate

In [38]:
print(df['Job Title'].value_counts())

Data Analyst                    200
Senior Data Analyst              38
Junior Data Analyst              25
Data Analyst Junior              17
Business Data Analyst            15
                               ...
Data Analyst (Junior)             1
Outsights Data Analyst            1
Data Analyst - Excel              1
Data Analyst - IntelliScript      1
Senior Quality Data Analyst       1
Name: Job Title, Length: 764, dtype: int64

In [39]:
print(df.Rating.value_counts())

3.9    117
3.7     97
3.5     87
3.6     83
3.8     82
4.1     78
3.3     75
4.0     72
5.0     70
3.4     65
3.1     55
3.2     52
4.2     32
3.0     29
2.9     28
4.6     28
4.3     24
4.5     23
2.8     22
4.4     19
2.7     16
4.8     11
2.5     10
4.9      9
4.7      7
2.4      5
2.6      4
2.2      2
2.0      1
2.3      1
2.1      1
1.8      1
Name: Rating, dtype: int64

In [40]:
df.Size.value_counts()

10000+ employees           320
1001 to 5000 employees     256
51 to 200 employees        223
201 to 500 employees       146
501 to 1000 employees      134
5001 to 10000 employees     78
1 to 50 employees           49
Name: Size, dtype: int64

In [41]:
df.Revenue.value_counts()

$100 to $500 million (USD)          207
$50 to $100 million (USD)           191
$10+ billion (USD)                  186
$2 to $5 billion (USD)              127
$10 to $25 million (USD)            112
$25 to $50 million (USD)             90
$1 to $2 billion (USD)               86
$500 million to $1 billion (USD)     75
$5 to $10 billion (USD)              56
$1 to $5 million (USD)               40
$5 to $10 million (USD)              26
Less than $1 million (USD)           10
Name: Revenue, dtype: int64

In [42]:
df.Competitors.value_counts()

NA                                                                 771
Adecco, Manpower                                                    14
Robert Half, Insight Global                                         14
TEKsystems, Insight Global, Accenture                               10
Google, Microsoft, Samsung Electronics                              10
                                                                  ...
Fiserv, First Data, Jack Henry & Associates                          1
Booz Allen Hamilton, Abt Associates, Oliver Wyman                    1
DP Electric, Helix Electric, Wilson Electric                         1
Big O Tires, Les Schwab Tire Centers, Pep Boys                       1
Centura Health, HealthONE, Denver Health and Hospital Authority      1
Name: Competitors, Length: 234, dtype: int64

In [43]:
df.Hourly.value_counts()

0    1206
Name: Hourly, dtype: int64

In [44]:
df['Annual min_salary'].value_counts()

37     64
57     61
42     57
60     52
43     51
35     49
41     46
53     44
51     41
46     40
50     39
47     31
73     30
55     29
65     26
30     26
49     23
48     23
27     22
58     19
24     19
40     19
34     18
44     18
89     18
76     18
64     18
74     17
28     17
97     17
29     16
93     16
98     16
110    16
59     16
54     16
67     15
77     15
69     15
45     15
113    13
38     12
63     12
82     11
26     11
99      9
84      8
78      7
68      6
32      4
31      3
36      2
Name: Annual min_salary, dtype: int64

In [45]:
df['Annual max_salary'].value_counts()

76     63
86     57
66     48
93     44
78     44
67     43
52     39
74     35
88     35
94     35
87     32
68     30
132    28
104    27
82     26
116    23
127    21
69     21
103    21
48     19
53     18
61     18
124    18
122    18
101    18
113    18
151    18
100    17
123    17
129    17
70     17
190    16
85     16
159    16
75     16
38     16
114    16
44     15
92     15
99     15
42     15
102    14
81     14
91     14
120    14
45     13
110    12
72     12
47     11
89     10
178     9
96      9
112     9
90      8
54      8
56      4
59      3
77      1
Name: Annual max_salary, dtype: int64

In [46]:
pd.set_option("display.max_rows", None)
df['Annual avg_salary'].value_counts()

59.5     47
68.0     42
72.0     39
63.0     34
56.0     33
59.0     30
40.0     30
99.0     29
61.5     24
78.5     24
80.5     22
39.5     22
73.5     22
51.0     21
62.0     20
77.5     20
66.5     20
75.5     19
36.0     19
120.0    18
52.5     18
92.0     18
47.5     18
88.5     18
41.5     18
78.0     18
51.5     17
113.0    17
98.5     17
106.0    16
58.0     16
53.5     16
33.5     16
64.5     16
150.0    16
63.5     16
126.0    16
104.5    15
98.0     15
40.5     15
79.5     15
38.5     15
76.0     15
74.0     14
66.0     14
92.5     14
69.0     14
70.0     14
68.5     13
122.5    13
69.5     13
53.0     12
73.0     12
89.5     12
85.0     12
60.5     12
36.5     11
71.5     11
54.0     11
79.0     11
81.0     10
80.0     10
138.5     9
42.0      8
87.0      8
91.0      7
57.0      7
100.0     6
61.0      6
44.0      4
45.0      3
64.0      2
60.0      1
Name: Annual avg_salary, dtype: int64

In [47]:
pd.set_option("display.max_rows", None)
df['CompanyName'].value_counts()

Staffigo Technical Services, LLC                        58
Diverse Lynx                                            22
Kforce                                                  19
Robert Half                                             14
Mondo                                                   14
Apple                                                   10
Apex Systems                                            10
eTeam Inc.                                              10
Reliable Software Resources                              9
TechUSA                                                  8
Citi                                                     7
MUFG                                                     7
The Bank of New York Mellon                              7
Capgemini                                                7
Collabera                                                7
Infotree Service Inc                                     6
Avani Technology Solutions                               6
Perficient                                               6
Molina Healthcare                                        6
Vaco                                                     5
Microsoft Corporation                                    5
JPMorgan Chase                                           5
Acumen                                                   5
Centene Corporation                                      5
The Judge Group, Inc.                                    5
Kelly                                                    5
22nd Century Technologies                                5
Praescient Analytics                                     5
Akraya Inc.                                              5
CYNET SYSTEMS                                            4
Net2Source                                               4
The Judge Group                                          4
AppleOne                                                 4
TEKsystems, Inc                                          4
Mount Sinai Medical Center                               4
Freedom Mortgage                                         4
ClientSolv Technologies                                  4
Orbis, Inc.                                              4
Cedars-Sinai                                             4
Lowe's                                                   4
Kaiser Permanente                                        4
Signature Consultants                                    4
Goldman Sachs                                            4
Mitchell Martin                                          4
Amyx, Inc.                                               4
NYU Langone Health                                       4
Oasis Systems                                            3
Costco Wholesale Corporation                             3
IPRO                                                     3
Integrated Resources                                     3
EY                                                       3
Zachary Piper Solutions, LLC                             3
J.P. Morgan                                              3
Flexport                                                 3
Deutsche Bank                                            3
Xoriant Corporation                                      3
Walt Disney Co.                                          3
Ascent                                                   3
InvenTech Info                                           3
CyberCoders                                              3
Software Guidance & Assistance                           3
Swoon                                                    3
Nesco Resource, LLC                                      3
Circle K Stores, Inc.                                    3
ICONMA                                                   3
Lockheed Martin                                          3
Autodesk                                                 3
Turner Broadcasting                                      3
TalentBurst, Inc.                                        3
Nationwide Children's Hospital                           3
DATA Inc.                                                3
CenturyLink                                              3
Intuit                                                   3
Artech LLC                                               3
Analytical Mechanics Associates                          3
Kelsey Seybold Clinic                                    3
Rockstar Games                                           3
Forfeiture Support Associates                            3
Amazon                                                   3
Diversant LLC                                            3
RGP                                                      3
Mount Sinai Health System                                3
Frontend Arts                                            2
UCSF Medical Center                                      2
CACI International                                       2
Child Mind Institute                                     2
Hinge Health                                             2
Fred Hutch                                               2
IntraEdge                                                2
Montefiore Medical                                       2
NVIDIA                                                   2
The Paragon Group                                        2
University of Chicago                                    2
ConsultNet, LLC                                          2
Shands Jacksonville                                      2
Lidl                                                     2
Jobot                                                    2
HireTalent                                               2
Twitter                                                  2
Impaq International, Llc                                 2
Epsilon Systems Solutions, Inc.                          2
Booz Allen Hamilton                                      2
Columbia University                                      2
Tempus                                                   2
QuinStreet                                               2
CRS Group                                                2
Precision technologies corp                              2
CDO Technologies Inc                                     2
Vivint Solar                                             2
xentity corporation                                      2
Bank of America                                          2
Northwell Health                                         2
Qualys                                                   2
IBM                                                      2
Apollo Global Management                                 2
Insight Enterprises, Inc.                                2
Yochana                                                  2
Wells Fargo                                              2
Crystal Equation                                         2
Illumina                                                 2
SCAN Health Plan                                         2
Wellcare                                                 2
TEKsystems                                               2
Strategic Staffing Solutions                             2
Mercury Insurance Group                                  2
Resource Logistics, Inc.                                 2
Genuent                                                  2
Russell Tobin & Associates                               2
Vaco Technology                                          2
Desert Financial Credit Union                            2
Google                                                   2
American Tire Distributors                               2
Netflix, Inc.                                            2
InfoVision, Inc.                                         2
TekCom Resources, Inc.                                   2
EDP World, Inc.                                          2
National Education Partners                              2
PruTech Solutions, Inc.                                  2
Warner Bros. Entertainment                               2
Delmarva Foundation                                      2
System Soft Technologies                                 2
Cadence Design Systems                                   2
HealthStream                                             2
BMO                                                      2
Connor Group                                             2
Focal Systems                                            2
amerihealth                                              2
Prudent Technologies & Consulting                        2
Avantor                                                  2
Mosaic Sales Solutions                                   2
VED Software Services, Inc.                              2
Web Shop Manager                                         2
Ascension                                                2
Crown Castle USA Inc                                     2
Oracle                                                   2
UBS                                                      2
Virtus Partners LLC                                      2
SAT Healthcare                                           2
RMS Computer                                             2
LanceSoft Inc                                            2
Boeing                                                   2
General Dynamics Information Technology                  2
MedSeek                                                  2
Criteo                                                   2
Horizon Blue Cross Blue Shield of New Jersey             2
Trinity Industries                                       2
RMS Computer Corporation                                 2
Seven Seven Softwares                                    2
Source of Future Technology Inc                          2
Wipro Ltd.                                               2
NTT DATA                                                 2
Walgreens                                                2
LendingTree, LLC.                                        2
Enquero Inc                                              2
VIVA USA INC                                             2
Ho Chunk                                                 2
The Ascent Services Group                                2
Tachyon Technologies LLC                                 2
AbbVie                                                   2
Arthur Lawrence                                          2
Eurofins                                                 2
Square                                                   2
First American Financial Corporation                     2
BMO Financial Group                                      2
BNY Mellon                                               2
Blue Shield of California                                2
GasPedal                                                 2
Halcyon Solutions, Inc.                                  2
AmeriHealth Caritas                                      2
Kelsey-Seybold Medical Group                             2
University of Texas at Arlington                         2
National Capitol Contracting (NCC)                       2
PROLIM Global Corporation                                2
Pushnami                                                 2
Community Behavioral Health                              2
Ampcus Incorporated                                      2
TSR, Inc.                                                2
Intercontinental Exchange, Inc.                          2
EmblemHealth                                             2
Harris County                                            2
John Wiley & Sons, Inc.                                  1
Fortinet                                                 1
eHealth                                                  1
Technosoft Corporation                                   1
US Tech Solutions, Inc                                   1
Cepheid                                                  1
Milestone Technologies Inc.                              1
Dexcom, Inc.                                             1
BD                                                       1
Stanford Health Care                                     1
Exact Sciences Corporation                               1
Lark Health                                              1
DynPro Inc.                                              1
SRA OSS                                                  1
Vertex Pharmaceuticals                                   1
Mackin                                                   1
SOFTHQ INC                                               1
Splunk                                                   1
Centrillion                                              1
Stanford University                                      1
Harris Computer                                          1
SAP                                                      1
World Wide Technology                                    1
ServiceLink, a Black Knight Company                      1
eDataForce consulting LLC                                1
Pinnacle Technical Resources, Inc.                       1
ADT                                                      1
Apptricity Corporation                                   1
Mary Kay                                                 1
RealPage                                                 1
McAfee                                                   1
North Central Texas Council of Governments               1
Atmos Energy Corp.                                       1
Federal Reserve Bank of Richmond                         1
Sunrise Systems, Inc.                                    1
The Carrera Agency                                       1
HCL America Inc.                                         1
Kubota Tractor                                           1
VITALWARE LLC                                            1
Dallas Independent School District                       1
Financial Additions                                      1
Dallas ISD                                               1
Hilltop Holdings                                         1
Match Group                                              1
Nokia                                                    1
Atos                                                     1
SBG Techology Solutions                                  1
Federal Reserve Bank                                     1
The Richards Group                                       1
Fairway Independent Mortgage Corporation                 1
Colfax Corporation                                       1
Zolon Tech Solutions Inc.                                1
Sycuan Casino                                            1
Poshmark                                                 1
Accounting Principals                                    1
Power Integrations                                       1
PDS Tech, Inc.                                           1
Iconma, L.L.C.                                           1
Netflix                                                  1
Zipongo                                                  1
MedImpact                                                1
Tesla Motors                                             1
Bandai Namco Entertainment America                       1
Alteryx                                                  1
LeanData                                                 1
Risk Management Solutions (RMS)                          1
ServiceLink                                              1
OSI Engineering                                          1
Peyton Resource Group (PRG)                              1
ArcBest                                                  1
California State University                              1
FirstAmerica                                             1
Employbridge                                             1
Molex                                                    1
DJO Global                                               1
Horn Solutions Inc.                                      1
ICONMA, LLC                                              1
Mindteck                                                 1
Onyx CenterSource                                        1
Akorbi                                                   1
Vera Institute of Justice                                1
Anzu Global                                              1
Rose International                                       1
Navient                                                  1
Briljent                                                 1
Upper Hand                                               1
BCforward                                                1
The Fountain Group                                       1
Keywords Studios                                         1
Kuehne + Nagel                                           1
Health & Hospital Corporation                            1
Heartland Payment Systems                                1
Franciscan Health                                        1
CNO Financial Group                                      1
Lionbridge                                               1
Washington Federal                                       1
TechDigital Corporation                                  1
Blue Origin                                              1
Allied Solutions                                         1
Concept Software & Services Inc                          1
Central Garden & Pet Company                             1
Hazelcast                                                1
Netpace, Inc.                                            1
Stem Inc                                                 1
VLink Inc.                                               1
Bank of the West                                         1
PRIMUS Global Services, Inc                              1
Bio-Rad                                                  1
University of California Berkeley                        1
Incedo Inc                                               1
Alliance IT                                              1
Square Trade                                             1
Next Level Business Services, Inc.                       1
GoAhead Solutions                                        1
Franklin Templeton Investments                           1
Sutter Health System                                     1
Subex                                                    1
Intelliswift Software Inc                                1
Protingent                                               1
DW Simpson                                               1
Charles Schwab Corporation                               1
Quicksilver Scientific, Inc                              1
Broadridge                                               1
Century Communities                                      1
Weston Solutions                                         1
Recondo Technology                                       1
Black Knight Financial Services                          1
CitiusTech                                               1
Global Healthcare Exchange                               1
V.L.S. Systems                                           1
GHX                                                      1
Telligen                                                 1
Arrow Electronics                                        1
Contingent Network Services                              1
TA Digital                                               1
Xcel Energy                                              1
Zen3 Infosolutions America Inc                           1
University of Georgia                                    1

In [48]:
df['State_Location'].value_counts()

 CA    305
 TX    210
 NY    166
 IL     90
 CO     58
 NC     57
 AZ     56
 PA     56
 NJ     54
 WA     36
 VA     30
 FL     20
 OH     20
 IN     17
 UT     14
 DE      9
 GA      4
 SC      2
 KS      2
Name: State_Location, dtype: int64

In [49]:
pd.set_option("display.max_rows", None)
df['Age'].value_counts()

14     76
22     50
20     49
24     45
23     44
26     44
25     36
18     33
27     30
21     29
56     29
11     24
16     23
28     23
17     22
12     20
32     20
15     19
38     18
55     17
39     16
30     16
46     15
19     15
74     15
9      14
31     14
76     13
10     13
37     13
42     13
13     13
33     12
223    10
52     10
8      10
47      9
60      9
238     9
158     8
29      8
99      8
40      8
34      8
210     7
45      7
77      7
87      7
83      6
54      6
65      6
41      6
49      5
130     5
108     5
75      5
35      5
71      5
58      5
120     5
73      5
61      5
43      4
153     4
4       4
44      4
36      4
84      4
118     4
53      4
181     4
167     3
132     3
7       3
51      3
5       3
106     3
50      3
152     3
134     3
133     3
92      3
66      3
116     3
85      3
6       3
59      3
69      2
121     2
177     2
67      2
62      2
3       2
70      2
155     2
89      2
148     2
138     2
126     2
170     2
115     2
111     2
86      2
154     2
90      2
205     2
140     2
136     2
160     2
63      2
78      1
103     1
157     1
166     1
110     1
131     1
215     1
172     1
101     1
324     1
91      1
150     1
98      1
129     1
340     1
147     1
105     1
146     1
237     1
113     1
125     1
117     1
96      1
57      1
185     1
190     1
194     1
124     1
94      1
109     1
165     1
127     1
104     1
142     1
64      1
163     1
204     1
137     1
100     1
68      1
192     1
48      1
88      1
169     1
Name: Age, dtype: int64

# Export out as Cleaned CSV for EDA and Machine Learning

In [50]:
df.columns

Index(['No.', 'Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply', 'Hourly', 'Annual min_salary', 'Annual max_salary',
       'Annual avg_salary', 'CompanyName', 'State_Location', 'Age',
       'Text/Description', 'JobSpilt', 'SeniorityRoles'],
      dtype='object')

In [51]:
df.to_csv("C:\\Users\\dinos\\OneDrive\\Desktop\\SC1015 LABs\\Data_Analyst_Job_DataSet_Cleaned.csv")

In [52]:
df_cleaned = pd.read_csv('Data_Analyst_Job_DataSet_Cleaned.csv')
df_cleaned.value_counts

<bound method DataFrame.value_counts of       Unnamed: 0   No.                                          Job Title  \
0              0     0  Data Analyst, Center on Immigration and Justic...
1              1     1                               Quality Data Analyst
2              3     3                                       Data Analyst
3              4     4                             Reporting Data Analyst
4              7     7                               Data Science Analyst
5              8     8                                       Data Analyst
6             10    10                                       Data Analyst
7             12    12                                       DATA ANALYST
8             13    13                                Senior Data Analyst
9             14    14                   Investment Advisory Data Analyst
10            17    17                              Clinical Data Analyst
11            18    18                            DATA PROGRAMMER/ANALYST
12            20    20                      Product Analyst, Data Science
13            22    22                     Data Analyst - Intex Developer
14            26    26               Data + Business Intelligence Analyst
15            30    30                                       Data Analyst
16            35    35  Analyst/Associate Global Markets Credit Data A...
17            38    38                      Data Science Analyst/Engineer
18            45    45                                       Data Analyst
19            47    47                                       Data Analyst
20            49    49                       Senior Analyst, Data Science
21            50    50                       Senior Data Analyst, Disney+
22            52    52                              Business Data Analyst
23            54    54        Data Scientist / Big Data Analytics Analyst
24            56    56  Principal Data Analyst, LATAM - Disney Streami...
25            57    57                                    Data Analyst II
26            59    59                                       Data Analyst
27            61    61     Data Analyst - Data Acquisition / Data Lineage
28            62    62     Data Analyst - Data Scanning utilizing Rochade
29            63    63                           Data Analyst - Stitching
30            64    64                                Junior Data Analyst
31            65    65                         Data Analyst, Retail Media
32            67    67                             Portfolio Data Analyst
33            69    69                             Data/Reporting Analyst
34            70    70                                     Data Analyst 2
35            73    73                       Data/Information Mgt Analyst
36            76    76                     Media Science Big Data Analyst
37            83    83                                    BA/Data Analyst
38            87    87                   Data Analytics Solutions Analyst
39            89    89                                       Data Analyst
40            91    91             Descriptive Analytics Data Analyst, IB
41            92    92                                       Data Analyst
42            93    93                                       Data Analyst
43            94    94                                       Data Analyst
44           101   101                        Data Analyst - IBM Tool Set
45           102   102                             Analyst-Data Integrity
46           103   103  Reference Data Operations Analyst - Index Inst...
47           107   107                                       Data Analyst
48           111   111  Data Analytics Analyst or Associate, Cowen Sus...
49           112   112                             Data Reporting Analyst
50           113   113                                       Data Analyst
51           115   115                                       Data Analyst
52           116   116                                   ERP Data Analyst
53           117   117                                       Data Analyst
54           121   121                                       Data Analyst
55           122   122                                Market Data Analyst
56           124   124                                Junior Data Analyst
57           125   125                Microsoft Dynamics CRM Data Analyst
58           126   126                              Practice Analyst Data
59           127   127          Buyside - Data Scientist/Research Analyst
60           129   129                    Electronic Trading Data Analyst
61           130   130          Data Analyst, Center for Developing Brain
62           133   133                          Data Analyst with Rochade
63           135   135                             Product Analyst - Data
64           136   136                                Senior Data Analyst
65           138   138  Market Research Data Analyst - Physician Techn...
66           141   141                            Data Collection Analyst
67           142   142                                       Data Analyst
68           144   144  Student Persistence Initiative Data Analyst/Sc...
69           147   147  Sr. Business Intelligence Engineer / Data Analyst
70           150   150                                       Data Analyst
71           152   152    Data Analyst I - Geriatrics and Palliative Care
72           154   154                               Data Analyst/Rochade
73           156   156                                       Data Analyst
74           158   158  Data Analyst II, Division of Gastroenterology ...
75           159   159              Data Analyst, Student Success Program
76           164   164      Data Analyst with Data Scanning and Profiling
77           165   165                 Business Analyst - Data Governance
78           168   168                    Research Analyst (Data Science)
79           169   169                            Data Management Analyst
80           171   171                  Healthcare Data/Reporting Analyst
81           173   173                         Sr. Data Profiling Analyst
82           175   175                                       Data Analyst
83           176   176                                       Data Analyst
84           177   177       Sr. Data Analyst, Revenue Analytics, Peacock
85           180   180  Senior Data Analyst - Data Cataloging / Data P...
86           184   184                                   GIS Data analyst
87           185   185            Junior Data Analytics Solutions Analyst
88           187   187                     Data Analyst w/Capital Markets
89           188   188       VP, Research Project Analyst/Data Management
90           190   190                            Data Management Analyst
91           191   191                            Data Governance Analyst
92           192   192                 Data Analyst, Enterprise Analytics
93           193   193  Data Analytics Solutions Analyst - Mid with Se...
94           195   195  Investment Management Summer Analyst Program -...
95           198   198          Sr Business /Data Analyst- Reference data
96           200   200                                SENIOR DATA ANALYST
97           209   209                       Data Analyst (35 hours/week)
98           211   211                                       Data Analyst
99           215   215                                       Data Analyst
100          217   217              Data Remediation Analyst-EK020719A/JL
101          218   218               Business Analyst - Chief Data Office
102          219   219  Senior Analyst, Data Instrumentation & Quality...
103          220   220                                   Sr. Data Analyst
104          221   221                        Big Data Programmer Analyst
105          224   224                            Data Governance Analyst
106          226   226        Financial Data Analyst - Accounting - D3529
107          228   228  Data Processing & Performance Analyst New York...
108          229   229                                       Data Analyst
109          232   232                       Business Analyst-Market Data
110          233   233  Content Analyst/Data BA-Bus/Tech Strategy - In...
111          235   235     Senior Analyst, AB Testing and Data Operations
112          237   237    Data Analyst I - Geriatrics and Palliative Care
113          239   239                   Senior Business and Data Analyst
114          240   240                                    Data Analyst II
115          241   241                                    Data Analyst II
116          243   243                       Lead Generation Data Analyst
117          245   245       Data Analyst I - Genetics & Genomic Sciences
118          246   246                         Data Reporting Analyst III
119          248   248                                Data Analyst - CBCH
120          249   249  Principal Data Analyst, LATAM Disney Streaming...
121          250   250                         Data Engineer/Data Analyst
122          251   251                    Technical Business/Data Analyst
123          254   254                      Senior Data Analyst - Rochade
124          256   256  2021 Summer Analyst Program- Data & Analytics ...
125          257   257                                  Data Analyst - QC
126          262   262                  Healthcare Data/Reporting Analyst
127          264   264        JPSC-8461 - Position: 13,52,53 Data Analyst
128          268   268       Data Analyst with Python or Python developer
129          269   269                    Data Entry Clerk / Data analyst
130          270   270     Senior Analyst, Data and Insights (Wirecutter)
131          273   273                            Data Governance Analyst
132          274   274                           Data Analyst with Python
133          277   277                              Analyst Business Data
134          280   280                      Consumer Lending Data Analyst
135          282   282  Business Analyst/PM/Data Analyst - Investment ...
136          285   285               TX Healthcare Data/Reporting Analyst
137          286   286         Senior Data Analyst - Regulatory Reporting
138          287   287                     Senior Specialist Data Analyst
139          288   288                  SQL Report Developer Data Analyst
140          290   290  Data Analyst,, Sales Operations - Oracle Data ...
141          292   292                     Senior Analyst, Data Analytics
142          293   293                      Senior Data Analyst (Product)
143          294   294  Senior Data Analyst - Data Cataloging / Data P...
144          295   295  2021 Summer Analyst Program- Data & Analytics ...
145          296   296                             Technical Data Analyst
146          297   297               Senior Analyst, Customer Master Data
147          298   298                       Data Analyst/Project Manager
148          299   299        Data Analyst II - Division of Endocrinology
149          300   300          Sr. Reference Data Business Analyst - SQL
150          302   302  Data Management Analyst (ADDM04) SEC SVCS OPS ...
151          303   303                        BA With Data Analyst Skills
152          304   304                    Data & Reporting Analyst, GNHCC
153          305   305       Principal Business Analyst - Data Governance
154          306   306    Business Analyst/Data Analyst - Capital Markets
155          307   307  .net, sharepoint, Java, Data analyst, Business...
156          309   309                      Consumer Lending Data Analyst
157          312   312                          Data Science Lead Analyst
158          314   314  Remote: Data Analyst (Data Lineage, Financial ...
159          317   317    Data Management, Firmwide Data Quality, Analyst
160          318   318    Compensation and Data Analyst (Human Resources)
161          319   319                                Senior Data Analyst
162          320   320  Data Analyst II, Division of Gastroenterology ...
163          321   321               NY Healthcare Data/Reporting Analyst
164          323   323     Big Data QA Analyst / QA Tester / Test Analyst
165          326   326            Data Analyst, Capital Markets (Manager)
166          329   329  CIB F&BM Global Program Management EMEA - Inte...
167          331   331                   Senior IT Technical Data Analyst
168          332   332  Data Analyst/Data Acquisition Speciliest with ...
169          333   333  Data Analyst/Data Scanning with Financial Indu...
170          335   335              Senior Data Analyst - Data Governance
171          336   336                       Senior Manager, Data Analyst
172          338   338                       Risk Adjustment Data Analyst
173          339   339                                   Data Analyst III
174          340   340                     Sr. Data Analyst, Retail Media
175          341   341                       Sr IT Technical Data Analyst
176          345   345                  Senior SQL Data Warehouse Analyst
177          346   346                                Data Analyst Junior
178          347   347               SR. Power BI with DAX - Data Analyst
179          349   349          Senior Solutions Analyst, Data Specialist
180          351   351                                    HR Data Analyst
181          352   352             Healthcare Senior Data Analyst - HEDIS
182          353   353                        Senior Data Quality Analyst
183          358   358  Senior Data Analyst, Gas Planning and Design E...
184          360   360                       Senior Data Business Analyst
185          361   361  Business Analyst/Data Analyst - Capital Market...
186          362   362  Firmwide Reference Data Operations, Pricing Op...
187          365   365  Senior Data Analyst - FHC - Family Support Center
188          368   368  Data Analyst/Project Manager in Jersey City, N...
189          370   370             Data Analyst with Data Lineage/Rochade
190          371   371  Senior Market Data Content Acquisition/Procure...
191          372   372  Sr. Specialist Reporting Data Analyst /Enginee...
192          373   373           Senior Business Analyst, Data Management
193          374   374  Data Science Analyst II - Mount Sinai Health P...
194          375   375               NY Healthcare Data/Reporting Analyst
195          377   377  Technical Business Analyst with Retail Banking...
196          378   378  Principal Sales Operations Analyst - Oracle Da...
197          379   379                         QA Production Data Analyst
198          380   380   JPSC-7462 - Data Analyst Lead - Sr. Tableau Lead
199          387   387  Specialist, Data and Reporting Analyst - IT Ch...
200          389   389                        Data Analyst III- SAS req'd
201          393   393                             Sr. Data Analyst - RWE
202          395   395            Senior Data Analytics Solutions Analyst
203          397   397                    Data Analyst - Cardiac Cath Lab
204          398   398                    Data Quality Management Analyst
205          400   400           Senior Teradata Developer / Data Analyst
206          406   406  Sr. Specialist Reporting Data Analyst -Technology
207          407   407                  Sr. Programmer Analyst - Big Data
208          409   409                              Data Analyst â Junior
209          410   410      Sr. Principal Metrics Analyst- Data Scientist
210          411   411                     Product & Pricing Data Analyst
211          412   412                                   SAP Data Analyst
212          415   415  Senior Data Analytics Solutions Analyst with S...
213          416   416  JPSC-7176 - Position 35, 59, 62, 100,101,102, ...
214          423   423                                       Data Analyst
215          424   424                                       Data Analyst
216          430   430                                  Data Analyst : 20
217          431   431  Data Intelligence - Product Data Quality Analy...
218          433   433                              Data Engineer/Analyst
219          437   437                                   Big Data Analyst
220          438   438                                Senior Data Analyst
221          441   441                                Senior Data Analyst
222          442   442                      Data Scientist/Analyst - Noke
223          443   443                        Data Analyst - W2 candidate
224          447   447                             Financial Data Analyst
225          450   450                a. Senior Data and Business Analyst
226          451   451                                  Fund Data Analyst
227          452   452    Sr Python Data Analyst(no c2c) contract w2 only
228          454   454                                       Data Analyst
229          456   456                        Data Analyst (Kings County)
230          457   457                   Tactical Data Link (TDL) Analyst
231          458   458                                       Data Analyst
232          459   459                               Data Science Analyst
233          460   460                                Junior Data Analyst
234          461   461                                Junior Data Analyst
235          462   462                                    Jr Data Analyst
236          466   466                                       Data Analyst
237          467   467                                       Data Analyst
238          469   469                     Finance Data Analytics Analyst
239          470   470  Business Intelligence/Data Analyst with Securi...
240          472   472                             Metrics & Data Analyst
241          473   473                  Tactical Data Link (TDL) Analyst-
242          475   475                                Data Analyst Junior
243          477   477                                 USMTF Data Analyst
244          478   478                                   Mid Data Analyst
245          480   480                        Retail Data Quality Analyst
246          481   481         USMTF Data Analyst with Security Clearance
247          482   482                Senior Data Strategy Analyst (SDSA)
248          484   484   Configuration and Data Management (C&DM) Analyst
249          485   485            Jr Management Analyst (Data Management)
250          486   486                                Senior Data Analyst
251          487   487                   Tactical Data Link (TDL) Analyst
252          489   489        Acoustics Data Analyst/Flight Test Engineer
253          492   492              Senior Data Management Analyst (SDMA)
254          494   494                  Data Warehouse Programmer/Analyst
255          497   497  Program Analyst - AIS/Maintenance Data System ...
256          498   498                         MSC Logistics Data Analyst
257          501   501          Sr Data Business Analyst - FacilitySource
258          503   503  NIWC Service Desk Analyst Component Enterprise...
259          504   504  NIWC Service Desk Analyst Component Enterprise...
260          505   505                                Junior Data Analyst
261          506   506                                       Data Analyst
262          507   507                                       Data Analyst
263          508   508                      AvMed Data Governance Analyst
264          509   509                         Data Management Analyst II
265          510   510                                Data Analyst Junior
266          511   511                              Data Analyst â Junior
267          512   512                        IT Analyst III Data Systems